sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t jvmachado/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jvmachado/react-test npm test

after_success:
  - docker build -t jvmachado/multi-client ./client
  - docker build -t jvmachado/multi-server ./server 
  - docker build -t jvmachado/multi-nginx ./nginx 
  - docker build -t jvmachado/multi-worker ./worker
  #Log docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Push images
  - docker push jvmachado/multi-client
  - docker push jvmachado/multi-server
  - docker push jvmachado/multi-nginx
  - docker push jvmachado/multi-worker